name: "publish npm"

on: push

jobs:
    publish:
        runs-on: ubuntu-latest
        steps:
            - name: checkout
              uses: actions/checkout@v2
            - name: node
              uses: actions/setup-node@v2
              with:
                  node-version: 20.11.1
                  registry-url: https://registry.npmjs.org
            - name: install dependencies
              run: npm install
              working-directory: .
            - name: build
              run: npm run build
              working-directory: .
            - name: list dist files
              run: ls -la src/dist
            - name: publish
              run: npm publish --access public
              working-directory: ./dist
              env:
                  NODE_AUTH_TOKEN: ${{secrets.NPM_AUTH_TOKEN}}
